# Generated by Django 5.0.4 on 2024-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('dw_cr1', models.FloatField()),
                ('dw_cr2', models.FloatField()),
                ('dw_cr3', models.FloatField()),
                ('dw_cr4', models.FloatField()),
                ('dw_cr5', models.FloatField()),
                ('dw_cr6', models.FloatField()),
                ('dw_cr7', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImpactWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('imp_cr1', models.FloatField()),
                ('imp_cr2', models.FloatField()),
                ('imp_cr3', models.FloatField()),
                ('imp_cr4', models.FloatField()),
                ('imp_cr5', models.FloatField()),
                ('imp_cr6', models.FloatField()),
                ('imp_cr7', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('level_desc', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('score_cr1', models.FloatField()),
                ('score_cr2', models.FloatField()),
                ('score_cr3', models.FloatField()),
                ('score_cr4', models.FloatField()),
                ('score_cr5', models.FloatField()),
                ('score_cr6', models.FloatField()),
                ('score_cr7', models.FloatField()),
                ('level', models.FloatField()),
                ('mandatory', models.FloatField()),
                ('domain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('service_group', models.CharField(max_length=200)),
                ('service_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
