# Generated by Django 4.2.13 on 2024-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRIapp', '0006_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heating', models.BooleanField(default=False)),
                ('cooling', models.BooleanField(default=False)),
                ('domain3', models.BooleanField(default=False)),
                ('domain4', models.BooleanField(default=False)),
                ('domain5', models.BooleanField(default=False)),
                ('domain6', models.BooleanField(default=False)),
                ('domain7', models.BooleanField(default=False)),
                ('domain8', models.BooleanField(default=False)),
                ('domain9', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
