# Generated by Django 4.2.13 on 2024-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRIapp', '0007_domaincontrol_delete_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_building_type', models.CharField(max_length=200)),
                ('selected_zone', models.CharField(max_length=200)),
                ('selected_H', models.BooleanField(null=True)),
                ('selected_H1a_level', models.PositiveIntegerField(null=True)),
                ('selected_H1b_level', models.PositiveIntegerField(null=True)),
                ('selected_H1c_level', models.PositiveIntegerField(null=True)),
                ('selected_H1d_level', models.PositiveIntegerField(null=True)),
                ('selected_H1f_level', models.PositiveIntegerField(null=True)),
                ('selected_H2a_level', models.PositiveIntegerField(null=True)),
                ('selected_H2b_level', models.PositiveIntegerField(null=True)),
                ('selected_H2d_level', models.PositiveIntegerField(null=True)),
                ('selected_H3_level', models.PositiveIntegerField(null=True)),
                ('selected_H4_level', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
